/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "on-error-container": "#93000a",
          "surface-container-highest": "#e0e3e5",
          "primary-fixed-dim": "#adc6ff",
          "on-tertiary-fixed-variant": "#5028ae",
          "on-background": "#191c1e",
          "inverse-primary": "#adc6ff",
          "error": "#ba1a1a",
          "secondary-container": "#61f5ed",
          "surface": "#f7f9fb",
          "primary-container": "#0070eb",
          "on-secondary": "#ffffff",
          "tertiary": "#6642c4",
          "surface-container-lowest": "#ffffff",
          "on-surface": "#191c1e",
          "on-primary": "#ffffff",
          "on-primary-fixed": "#001a41",
          "on-primary-fixed-variant": "#004493",
          "secondary-fixed": "#65f8f0",
          "on-secondary-fixed-variant": "#00504d",
          "surface-variant": "#e0e3e5",
          "background": "#f7f9fb",
          "outline-variant": "#c1c6d7",
          "tertiary-container": "#7f5ddf",
          "on-tertiary": "#ffffff",
          "surface-container": "#eceef0",
          "surface-container-high": "#e6e8ea",
          "on-tertiary-fixed": "#21005e",
          "primary-fixed": "#d8e2ff",
          "on-secondary-container": "#006f6a",
          "inverse-surface": "#2d3133",
          "inverse-on-surface": "#eff1f3",
          "tertiary-fixed": "#e8ddff",
          "surface-dim": "#d8dadc",
          "on-surface-variant": "#414755",
          "on-secondary-fixed": "#00201e",
          "surface-container-low": "#f2f4f6",
          "surface-bright": "#f7f9fb",
          "on-error": "#ffffff",
          "primary": "#0058bc",
          "surface-tint": "#005bc1",
          "tertiary-fixed-dim": "#cebdff",
          "secondary": "#006a66",
          "error-container": "#ffdad6",
          "secondary-fixed-dim": "#3fdbd4",
          "on-tertiary-container": "#fffbff",
          "on-primary-container": "#fefcff",
          "outline": "#717786"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "spacing": {
          "stack-md": "1rem",
          "stack-lg": "1.5rem",
          "stack-sm": "0.5rem",
          "gutter": "0.75rem",
          "glass-padding": "1.25rem",
          "container-margin": "1rem"
      },
      "fontFamily": {
          "body-lg": ["Inter"],
          "headline-md": ["Inter"],
          "label-sm": ["Inter"],
          "headline-xl": ["Inter"],
          "label-lg": ["Inter"],
          "headline-lg": ["Inter"],
          "body-md": ["Inter"]
      },
      "fontSize": {
          "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
          "headline-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
          "label-sm": ["10px", {"lineHeight": "12px", "fontWeight": "500"}],
          "headline-xl": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
          "label-lg": ["12px", {"lineHeight": "16px", "fontWeight": "600"}],
          "headline-lg": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
          "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
